# Site settings
name: Rachel Beaulac
title: Rachel Beaulac
description: energy industry professional
url: http://noodlesoup.online
baseurl: ''
email: rachelbeaulac@protonmail.com
# cover: https://bchiang7.github.io/img/og.png
# logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: http://noodlesoup.online/resume.pdf
social:
  - title: email
    url: mailto:rachelbeaulac@protonmail.com
  - title: linkedin
    url: https://linkedin.com/in/rachel-beaulac
  - title: github
    url: https://github.com/noodleswoop
  - title: vsco
    url: https://vsco.co/soupenjoyer

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
